### ISSUE TITLE
Constraint Tolerance not satisfied ?

### ISSUE THREAD

**Issue by VishnuDevA7** [ImperialCollegeLondon/ICLOCS#9] opened 2020-05-26 08:12 UTC
I am trying a multi-phase optimization problem with 22 decision variables and 40 nodes with problem scaling, mesh-refinement, n-p method, etc. I set my convergence and all constraints' tolerances to be 1e-8. IPOPT solves for the problem in less than 20 iterations and returns "Optimal solution found". However, when solutions are plotted, I see a lot of chattering in the optimal states and controls and the "Maximum Absolute Constraint Violation" is quite high (> 10). Is this related to scaling or is there a bug in the transcription ? I have tried a lot of variation in the options settings and end up with more or less similar chattering and constraint violations. The problem persists even when I try only a part of the problem in single phase.

**Comment by yuanbonie** [comment] 2020-05-26 09:55
When solving a continous time OCP with direct collocation transcription and discretization methods, satisfation of dynamic equations and constraints are only guaranteed at collocation points. The NLP solution is only sampled points, thus the continous trajectory in between collocation points need to be approximated through interpolation techniques. Therefore solving the NLP to which ever small NLP tolerances have no direct correlation with the accuracy of the solution to the continous-time OCP. Once the NLP is solved, the errors of the continous trajectory need to be analyzed and if necessary (when they are not within the tolerance you have defined), approperate changes need to be made to the discretization mesh (i.e. mesh refinement) and the problem have to be repetively solved until the torlerance you have defined is satisfied (i.e. the tolerance you have specified in ICLOCS problem formulation only enforced under the mesh refinement framework). For detailed understanding, I suggest you to read our paper for some of the details regarding solution accuracy: https://ieeexplore.ieee.org/abstract/document/8733053/. If you do not have access to IEEE resources, you can search the paper title and all papers are available as arxiv prepaints. 

However, there will be cases where mesh refinement scheme do fail to converge, and one of them is the issue of singular control (or singular arc) charaterised by large fluctuations/ringings in the solution, I guess this would be the chattering you have described. Removal of singular arc can be really challenging however it can not be simply resolved by trying different option settings. Some of the easier solutions you may wanna to check:

- If the singular arc is caused by a linear control in the form of x_n_dot=constant×u_k with simple bounds on u_k, and x_n appears elsewhere in the dynamic equations or in the objective nonlinearliy, then you can view constant×u_k_upper and constant×u_k_lower as rate constraints for x_n. ICLOCS support a different way of implementing rate constraints (with problem.inputs.url and problem.inputs.uru) tha avoids the singular arc ringings particular for this case (see https://ieeexplore.ieee.org/abstract/document/9007714 for more details on singular arc and rate constraints)
- If the singular arc only happens on certain intervals of the solution, you may use a multiphase formulation and for the phase that is known to exhibit singular arc, derive and implement additional constraints that are known as singular arc conditions. See the Goddard rocket example (example 4.9 in Bett's book https://epubs.siam.org/doi/book/10.1137/1.9780898718577) for details. You may also wanna to check http://www.ee.ic.ac.uk/ICLOCS/ExampleGoddardRocket1.html and http://www.ee.ic.ac.uk/ICLOCS/ExampleGoddardRocket2.html to compare the problem formulations in each cases. 
- Finding causes for singular arc and appropriate solutions to that can be challenging. Thus practially some people would choose to regularize the problem instead. For example, if you see your input variable u_k is ringing, you may suppress it by adding additional term in the objective function, e.g. with: J_new=J_old+rho*int_t0^tf u_k.^2 dt, with a choice of rho that is sufficiently large to be effective but also sufficiently small to ensure difference between J_new and J_old are neglectably small. This may not be easily obtained and you might need to have a regularization strategy to gradually change rho and warm start the solve. In ICLOCS, you can take advantage of the automatic regularization function (search automatic regularization function on http://www.ee.ic.ac.uk/ICLOCS/GetStartedProblemSingle.html to see how that can be configured). 
- Take a look at our list of examples (http://www.ee.ic.ac.uk/ICLOCS/Examples.html) to see different problems with singular arc and how they were dealt with. We are currectly working towards a new type of transcription method that might avoids these troubles as in direct collocation. We had a few demos in our simple examples (e.g. http://www.ee.ic.ac.uk/ICLOCS/ExampleVanderPalOscillator.html), however it still needs lots of development to be able to support a multi-phase complex problem, and work out of the box,

**Comment by VishnuDevA7** [comment] 2020-05-26 16:08
Thanks so much for the extensive reply. I will close this as I understand the problem does not pertain specifically to this library.

**Closed as completed** 2020-05-27 17:03 UTC
